#include "Common.h"

int main(int argc, char * arg[])
{
	bool run = true;

	//init everything - SDL, if it is nonzero we have a problem
	if (SDL_Init(SDL_INIT_EVERYTHING) != 0)
	{
		std::cout << "ERROR SDL_Init" << SDL_GetError() << std::endl;

		return -1;
	}

	//Create Window
	SDL_Window * window = SDL_CreateWindow("SDL", // Window title
						SDL_WINDOWPOS_CENTERED,  // x position, centered
						SDL_WINDOWPOS_CENTERED,  // y position, centered
						640,					  // Width, in pixels
						480,					  // height, in pixels
						0						  // flags
						);

	//Value to hold the event generated by SDL
	SDL_Event event;
	//Game Loop
	while (run)
	{
		//While we still have events in the queu
		while (SDL_PollEvent(&event))
		{
			//Get event type
			if (event.type == SDL_QUIT || event.type == SDL_WINDOWEVENT_CLOSE)
			{
				//Set our boolean which controls the loop to false
				run = false;
			}
		}
	}

	SDL_DestroyWindow(window);
	SDL_Quit();
    return 0;
}
